{
 "title": "VMware vSphere  - Hosts",
 "description": "VMware vSphere Dashboard - Hosts (Grafana 8.x / InfluxDB v2.0)",
 "tags": [
  "VMware",
  "vSphere Hosts",
  "vSphere Telegraf",
  "influxdb v2.0"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "datasource", "query": "influxdb" },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> keep(columns: [\"vcenter\"])\r\n  |> distinct(column: \"vcenter\")\r\n  |> group()"
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_cluster_cpu\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] == \"${vcenter}\")\r\n  |> keep(columns: [\"clustername\"])\r\n  |> distinct(column: \"clustername\")\r\n  |> group()\r\n"
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] == \"${vcenter}\")\r\n  |> keep(columns: [\"esxhostname\"])\r\n  |> distinct(column: \"esxhostname\")\r\n  |> group()"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] == \"${vcenter}\")\r\n  |> keep(columns: [\"dsname\"])\r\n  |> distinct(column: \"dsname\")\r\n  |> group()"
   },
   {
    "name": "esxiarm",
    "label": "ESXi ARM Server",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_esxi_arm\")\r\n  |> keep(columns: [\"hostname\"])\r\n  |> distinct(column: \"hostname\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  { "title": "$esxi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "esxi" },
  {
   "title": "ESXi VM Quick Overview",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_sys\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_latest\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usagemhz_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\" or r[\"_field\"] == \"totalCapacity_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: float(v: r.usage_average) * float(v: r.totalCapacity_average) / 100.00 * 1024.00 }))\r\n  |> group(columns: [\"esxhostname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"instance-total\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Utilization Avg %",
   "type": "timeseries",
   "description": "CPU usage as a percentage during the interval.",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU usage % $tag_cpu",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"instance-total\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "RAM usage %",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Ready in miliseconds",
   "type": "timeseries",
   "description": "Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "alias": "CPU Ready",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ready_summation\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "ready_summation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "Network utilization (combined transmit-rates and receive-rates) during the interval.",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$tag_interface bytesRx",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytesRx_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"_field\",\"interface\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "bytesRx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "$tag_interface bytesTx",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytesTx_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "bytesTx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Latency",
   "type": "timeseries",
   "description": "The average time a read, or write, from the virtual disk takes.",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Write - $tag_disk",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_disk",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalReadLatency_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"_field\",\"disk\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
     "select": [
      [
       { "params": [ "totalReadLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "Read - $tag_disk",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_disk",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalWriteLatency_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"_field\",\"disk\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
     "select": [
      [
       { "params": [ "totalWriteLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Adapter IOPS",
   "type": "timeseries",
   "description": "The average time a read, or write, from the datastore takes.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_adapter Read",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "adapter" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_storageAdapter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"numberReadAveraged_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
     "select": [
      [
       { "params": [ "numberReadAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "$tag_adapter Write",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "adapter" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_storageAdapter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"numberWriteAveraged_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "numberWriteAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "ARM - $esxiarm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "repeat": "esxiarm",
   "collapsed": true,
   "panels": [
    {
     "title": "ESXi VM Quick Overview",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Uptime",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_sys",
       "select": [
        [
         { "params": [ "uptime_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "CPU Usage MHz",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usagemhz_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "RAM Usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "query": "SELECT last(\"totalCapacity_average\") * (last(\"usage_average\")) / 100 * 1024 FROM \"vsphere_host_mem\" WHERE (\"esxhostname\" =~ /^$esxi$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "active_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "CPU Usage %",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "RAM Usage %",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "CPU Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_esxi_arm",
       "select": [
        [
         { "params": [ "boardtemp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$esxiarm$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Utilization Avg %",
     "type": "graph",
     "description": "CPU usage as a percentage during the interval.",
     "gridPos": { "h": 7, "w": 6, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "percent", "label": "CPU Utilization %" }
     ],
     "targets": [
      {
       "alias": "CPU usage % $tag_cpu",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "percent", "label": "RAM Usage in %" }
     ],
     "targets": [
      {
       "alias": "RAM usage %",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Temperature",
     "type": "graph",
     "description": "CPU Temperature",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius", "label": "CPU Temperature in Celsius" }
     ],
     "targets": [
      {
       "alias": "CPU Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_esxi_arm",
       "select": [
        [
         { "params": [ "boardtemp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$esxiarm$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "graph",
     "description": "Network utilization (combined transmit-rates and receive-rates) during the interval.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "KBs", "label": "Network Usage" }
     ],
     "targets": [
      {
       "alias": "$tag_interface bytesRx",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_net",
       "select": [
        [
         { "params": [ "bytesRx_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "$tag_interface bytesTx",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_net",
       "select": [
        [
         { "params": [ "bytesTx_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Disk Latency",
     "type": "graph",
     "description": "The average time a read, or write, from the virtual disk takes.",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "none", "label": "KBps" }
     ],
     "targets": [
      {
       "alias": "Write - $tag_disk",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "disk" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_disk",
       "select": [
        [
         { "params": [ "totalReadLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "Read - $tag_disk",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "disk" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_disk",
       "select": [
        [
         { "params": [ "totalWriteLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "Storage Adapter IOPS",
     "type": "graph",
     "description": "The average time a read, or write, from the datastore takes.",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "IOPS" }
     ],
     "targets": [
      {
       "alias": "$tag_adapter Read",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "adapter" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_storageAdapter",
       "select": [
        [
         { "params": [ "numberReadAveraged_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "$tag_adapter Write",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "adapter" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_storageAdapter",
       "select": [
        [
         { "params": [ "numberWriteAveraged_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Ready in miliseconds",
     "type": "graph",
     "description": "Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval.",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
     "yaxes": [
      { "format": "none", "label": "ms" }
     ],
     "targets": [
      {
       "alias": "CPU Ready",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "ready_summation" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Contact me:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 72 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}